config/routes.rb
Rails.application.routes.draw do
  # get 'events/index'
  # get 'users/user'
  root 'events#index'
  resources :events, only: %i[index new create show], to: 'show'
  resources :users, only: %i[index new create show]
  resources :sessions, only: %i[new create destroy]
  resources :invitations, only: %i[create]

  scope :sessions do
    get 'sign_out' => 'sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :description, :location, :date, presence: true
  belongs_to :creator, class_name: 'User'

  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations, source: :attendee

  scope :upcoming_events, -> { where('date >= ?', Time.zone.now) }
  scope :prev_events, -> { where('date < ?', Time.zone.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates_uniqueness_of :name

  has_many :events, foreign_key: :creator_id, class_name: 'Event'

  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_is_logged_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_is_logged_in?
    session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    # @events = Event.where(creator_id: session[:user_id].to_i).order(date: :asc)
    @events_prev = Event.prev_events
    @events_next = Event.upcoming_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:notice] = 'Event created successfully'
      redirect_to events_path
    else
      flash[:alert] = 'Event is not created, try again'
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @creator = User.find(@event.creator_id)
    # @attendees = User.joins('INNER JOIN invitations ON users.user_id=invitations.attendee').where('invitations.attended_event' => @event.id)
    @event.attendees.each do |event|
      @users = User.where.not(name: event.name).where.not(name: @event.creator.name)
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    event_id = params[:event_id]
    @attendee = Invitation.find_or_initialize_by(attendee_id: current_user.id, attended_event_id: event_id)
    redirect_to root_path if @attendee.save
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(name: params[:session][:user])
    @user ||= User.find(params[:session][:user].to_i)

    if @user
      session[:user_id] = @user.id
      session[:username] = @user.name
      redirect_to user_path(@user)
    else
      flash.now[:danger] = 'Wrong login info'
      render 'new'
    end
  end

  def destroy
    reset_session
    # session[:username] = nil
    flash[:success] = 'Log out successfully'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    # @events = Event.where(creator_id: session[:user_id].to_i).order(date: :asc)
    @upcoming_events = current_user.events.upcoming_events
    @past_events = current_user.events.prev_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(sign_up_params)
    if @user.save
      flash[:notice] = 'User created successfully'
      session[:user_id] = @user.id
      session[:username] = @user.name
      redirect_to user_path(@user)
    else
      flash[:alert] = 'User not created, please try again'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    session[:username] = nil
    flash[:success] = 'Log out with succes'
    redirect_to root_path
  end

  private

  def sign_up_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All the events</h1>

<div class="row">
  <div class="col-md-6">
  <h2>Past</h2>
    <% @events_prev.each do |event| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2"><%= link_to event.name, event_path(event) %> </h5>
        <p class="card-text"><%= event.description %></p>
        <p><strong>Location: </strong><small class="card-text"><%= event.location %></small></p>
        <p><strong>Date: </strong>
          <small class="card-text">
            <strong><%= event.date %> </strong>
            <!--<em>14:00:00</em>-->
          </small>
        </p>
      </div>
    </div>
    <br/>
    <% end %>
  </div>
  <div class="col-md-6">
  <h2>Future</h2>
  <% @events_next.each do |event| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2"><%= link_to event.name, event_path(event) %> </h5>
        <p class="card-text"><%= event.description %></p>
        <p><strong>Location: </strong><small class="card-text"><%= event.location %></small></p>
        <p><strong>Date: </strong>
          <small class="card-text">
            <strong><%= event.date %></strong>
            <!--<em>14:00:00</em>-->
          </small>
        </p>
        <% if user_is_logged_in? %>
          <%= render 'invitations/invitation', event: event %>
        <% end %>
      </div>
    </div>
    <br/>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h1 class="text-center">Create Event</h1><br />
      
      <%= form_for(@event) do |f| %>
        <div class="form-group">
            <%= f.text_field :name, autofocus: true, placeholder: "Event Title", class: "form-control"  %>
        </div><br />
        <div class="form-group">
            <%= f.text_area :description, placeholder: "Event Description", class: "form-control"  %>
        </div><br />
        <div class="form-group">
            <%= f.text_field :location, placeholder: "Event Location", class: "form-control"  %>
        </div><br />
        <div class="form-group">
          <%= f.datetime_select :date, :ampm => true, :minute_step => 15 %>
        </div><br />
        <div class="actions">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/events/show.html.erb
<div class="row mt-4">
  <div class="col-md-6 mb-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2"><%= @event.name %>
        <small class="float-right">Hosted by: <%= @event.creator.name  %> </small></h5>
        <p class="card-text"><%= @event.description %></p>
        <p><strong>Location: </strong><small class="card-text"><%= @event.location %></small></p>
        <p><strong>Date: </strong>
        <small class="card-text">
            <strong><%= @event.date.to_s.split(' ').first %> </strong>
            <em><%= @event.date.to_s.split(' ')[1] %></em>
        </small>
        </p>
      </div>
    </div>
  </div>

    <div class="col-md-3 mb-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2">List of Attendees</h5>
        <% @event.attendees.each do |attendee|%>
            <p><strong><%= attendee.name %></strong></p>
        <% end %>
      </div>
    </div>
  </div>

  
</div>

app/views/invitations/_invitation.html.erb
<% unless current_user.attended_events.include?(event) %>
  <%= form_with(model: @invitation, url: invitations_path, method: 'POST', local: true) do |form| %>
    <div class="forms mb-4">
      <%= form.hidden_field :event_id, class: 'form-control', value: event.id %>
      <div class="actions">
        <%= form.submit 'Attend Event', class: 'btn btn-primary mt-2' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" %>
    
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path%>">Private Events</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <p class="control">
            <% if user_is_logged_in? %>
            <h5><%= link_to session[:username], users_path, class: "nav-link" %></h5>
            <p class="control">
              <%= link_to "Create Event", new_event_path, class: "nav-link" %>
            </p>
            <p class="control">
              <%= link_to "All Event", events_path, class: "nav-link" %>
            </p>
            <p class="control">
              <%= link_to "Sign Out", sign_out_url, class: "nav-link" %>
            </p>
            <% else %>
            <p class="control">
              <%= link_to "Sign Up", new_user_path, class: "nav-link active" %>
            </p>
            <p class="control">
              <%= link_to "Sign In", new_session_path, class: "nav-link" %>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>All Members Profile<h1>
<% @users.each do |user| %>
<h2><%= user.name%></h2>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h1 class="text-center">Sign Up</h1><br />
      <%= form_for(@user) do |f| %>
        <div class="form-group">
            <%= f.text_field :name, autofocus: true, placeholder: "Enter a username", class: "form-control"  %>
        </div>
        <br />
        <div class="actions">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="text-center"><%= session[:username] %> Events</h1>
<br />
<br />
<div class="row">
  <div class="col-md-6">
  <h2>Past</h2>
    <% @past_events.each do |event| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2"><%= link_to event.name, event_path(event) %> </h5>
        <p class="card-text"><%= event.description %></p>
        <p><strong>Location: </strong><small class="card-text"><%= event.location %></small></p>
        <p><strong>Date: </strong>
          <small class="card-text">
            <strong><%= event.date %> </strong>
            <!--<em>14:00:00</em>-->
          </small>
        </p>
        <%= link_to "View Event", event_path, class: "btn btn-primary" %>
      </div>
    </div>
    <br/>
    <% end %>
  </div>
  <div class="col-md-6">
  <h2>Future</h2>
    <% @upcoming_events.each do |event| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2"><%= link_to event.name, event_path(event) %> </h5>
        <p class="card-text"><%= event.description %></p>
        <p><strong>Location: </strong><small class="card-text"><%= event.location %></small></p>
        <p><strong>Date: </strong>
          <small class="card-text">
            <strong><%= event.date %> </strong>
            <!--<em>14:00:00</em>-->
          </small>
        </p>
        <%= link_to "View Event", event_path, class: "btn btn-primary" %>
      </div>
    </div>
    <br/>
    <% end %>
  </div>
</div>